# Generated by Django 3.2 on 2021-12-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='option',
        ),
    ]
